### ISSUE TITLE
"to be empty" assertion is not implemented for Map

### ISSUE THREAD

**Issue by indeyets** [erikmueller/unexpected-immutable#18]
`expect(Map(), 'to be empty')` fails with: "TypeError: subjectType.getKeys is not a function"

it should check `.size` instead, probably

**Comment by erikmueller** [comment]
That's true @indeyets . Can you check if #19 solves your issue?

**Comment by erikmueller** [comment]
Should be included in 0.3.0. Feel free to reopen if sth went wrong (I had some otp issues with current & npm).
